# Generated by Django 2.2.1 on 2019-06-09 22:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('location', models.CharField(max_length=150)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('complement', models.CharField(blank=True, max_length=256, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Address: Address',
                'verbose_name_plural': 'Address: Addresses',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('function', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('presentation', models.CharField(blank=True, max_length=500, null=True)),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), size=3)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('action_area', models.IntegerField(choices=[(0, 'Saúde'), (1, 'Educação'), (2, 'Esportes'), (3, 'Cultura'), (5, 'Tecnologia'), (6, 'Sustentabilidade'), (7, 'Comunidade'), (8, 'Meio Ambiente'), (9, 'Mulheres'), (10, 'Idosos'), (11, 'Outros')])),
                ('logo_path', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='core.Address')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.IntegerField(choices=[(0, 'Blog/Site'), (1, 'Instagram'), (2, 'Facebook'), (3, 'Twitter'), (4, 'Youtube'), (5, 'Outro')])),
                ('type_name', models.CharField(blank=True, help_text='Used for type "other"', max_length=64, null=True)),
                ('address', models.CharField(max_length=512)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='core.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=60)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_password', to='core.Employee')),
            ],
            options={
                'verbose_name': 'Employee: EmployeePassword',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='core.Organization'),
        ),
    ]
