# Generated by Django 2.2.1 on 2019-06-16 02:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190615_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_session', to='core.Employee')),
            ],
            options={
                'unique_together': {('uuid', 'created_at')},
            },
        ),
    ]
