# Generated by Django 2.2.1 on 2019-06-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employeesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationmedia',
            old_name='address',
            new_name='path',
        ),
    ]
