# Generated by Django 2.2.1 on 2019-06-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190618_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
