# Generated by Django 2.2.1 on 2019-06-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190618_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='presentation',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
