# Generated by Django 2.2.1 on 2019-06-18 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190618_0115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='logo_path',
            new_name='logo',
        ),
    ]
